sudo: required
language: bash
services: docker
env:
  matrix:
  - ARCH=x86_64 PUID=1000 PGID=1000
  - ARCH=armhf PUID=1001 PGID=1001
  global:
  - secure: EOwuNaXTnELAe1Zpg37tlOPQb/Biq7FRe/Pa5svd+6Ap5GVwAMGWl7Yymgd4R3+dYwpJdUTUT7JwkT0WVIF/rio7NaHQe1rmbJquuasZU0QoE0Zed04YXMoIfEY6hYHNks7nNsdskIEMFsr5mg7qMXdS5Jl/WFNyUSfxSXBC6/vTmk0rZW363ZJlPwi1fbhVwNuCRh8i8MyW1+PV18Wy0QS+VdENBVQRGK39vCyQLVqopF0nEkdmBojZ8e2QU86hwVnAou4fUqFVZwI8a4ruSB3jSHVMvAhGIZAwpuXgIMUgNcm1T/RF5aOv7A+Iq6KkPo7Srrpx50q0/Oir1kuzt95XSDj9jPWTIkCtgezioLLLi+xZmmahCG1yu8yW91viJogr7yBQDyYL1TudXeyIKy6KSt3UHI8WmtpreHG1t9Mdf0GH6PIRrRZR/eJ7728WkZJ47g0bodKeeGeJw/5lfLI2HBRfwgJa08tCBBapnVFZthHNhXyxbxUXIEhI+bPy6k0Fu+QaLigd7aHPUOBbuzLEyeVV3q3+/l+wSkBjewHGNnYIlrA1WAjc91H9TYLrqnGXJh7RpJ68N2IIsOuO4RQ4Zt/m736q4QiHSx0AXmEVDkDtaRhZPKjHK8HbCm0Te5Fov0EjnPA8ZaHXJVs/NP3RcRi4wHWG+S1GP6mlQ9o=
  - secure: IzqB1tmcITDeoJQbvXWYQRMzhPEo2+KHIfsK7KvaaRznBTuHtCbAZtRtAca5hppBqR8mGJBHzX7BQ2UV7cFzZ/EpsxLtywq0ZytQdYiGujK4WfNbOT6/ZezHjK8wmwgO3zGXWgL2N1/6gSSxhHuKcu3vJNY5s64aYqTOVEcgREk9PjX+XszVGJyK9tCS8UpmVoyi1j9O5s0/ELOC99eR0m+adGtWSYv02NUINPvCpXcY5QjwWhMjFmbIslnx4DNaWdE6ZcHBoWA+S6qh07K++T2N3xQGGsK3W/EowiOknRZeDXSSJ1oALmlFunBbgPt6u83Miw0VYCYVF8snwv7Xj1b+KDPgd+BASGLHZToeP8RBBInA1HUuwOu+NaiztdyXQu6pCFVcDXLY/zwYtTO/2KCpSwnGjQBIo6xLyItIuJoHWdEdjqsjSn5yOi+/hb9Eibn4O6oneEwud6XVZtpOP75LU1KNVz3wr1hzAve7IJRJ17Qz2Ll/h6fc1c21qprnu2XnTDSAvCYjsMmv7mpE7hNbUoROQAeTN2LpT0q5Q7qEUt0jZvAGkoQrflcIMpGUfz52JXUu4m4fWCPmzxrMzvLIgDXvLzlFQRYziZHZVM5oaffuzzeD+s3u04CU7LGxJOA5sx9yxOx+xkBLzWojXcM8Y5cCRpxHdQOpwC96oKk=
install: true
before_script:
- docker --version
- make --version
script:
- make ARCH=${ARCH} PUID=${PUID} PGID=${PGID} build test
after_success:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- make ARCH=${ARCH} push
after_script:
- docker logout
- make clean
